#!/usr/bin/perl
# $Id$
if(-e "ChangeLog") {
    open(X,"new")||die("can't open 'new'\n");
    open(F,"TodayFixes")||die("can't open TodayFixes\n");
    while(<F>) {
	$id=$_ if /^\/\*/;
	$fixes++ if /^(\.|---)/;
	push(@fix,$_) if($fixes==1);
	push(@txt,$_) if($fixes==4);
    }
    open(F,">TodayFixes")||die("can't create TodayFixes\n");
    print F "$id---\n";
    print F <X>;
    print F ".\nprevious:\n";
    print F @fix;
    print F @txt;
    close(X,F);
    unlink("ChangeLog");
}
system("cvs2cl.pl -r -F trunk -I ChangeLog -I TodayFixes -I cvsdate.h -I 1234 -I cvs_com --no-wrap -S");
exit if($?>>8);
unlink("ChangeLog.bak");
system('date +\'char cvsdate[]="%Y-%m-%d %H:%M";\' >src/cvsdate.h');
#date +'char cvsdate[]="%Y-%m-%d %H:%M";' >src/cvsdate.h
system("cvs com -F new");
unless($?>>8){truncate("new",0);}
