#!/bin/sh
# sample of script for run in `runonchat'
# $Id$
for a in 1 2 3 6 5 4 8 6 20 10; do
    echo -en "\033[11;300]\033[10;${a}00]\a\033[10]\033[11]" >/dev/tty12
    echo -n|cat
done
play /path/to/chat.wav
